### ISSUE TITLE
memory corruption in Perl stack during signal emission

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#1233]
https://github.com/irssi/irssi/blob/master/src/perl/perl-signals.c#L209

crash on SvOK

reported by @RealKindOne

**Comment by RealKindOne** [comment]
I finally managed to figure out what exactly triggers the crash reliably for me.

I use trigger.pl with this, ```-send_command -regexp '\s+$' -replace ''```. 

Typing ```/clearquery ``` with a space at the end triggers the crash, since trigger.pl is doing some stuff.

I guess this takes 1000+ query windows with activity opened? I have no idea. 

I have irssi localhost'd 700+ connections into my znc with 1300+ query windows. 

https://github.com/RealKindOne/crashy

1, Clone repo.
2, Start znc (will not connect to anything, no server addresses).
3, Start irssi. 
4, Watch irssi localhost 700+ connections into ZNC.
5, Type ```/clearquery ```, with a space at the end.
6, Watch irssi crash.

**Comment by ailin-nemui** [comment]
Thanks for this! I think I can even repro the crash just with your config, without ZNC. With the patch applied, it does not crash for me, can you double check?
