### ISSUE TITLE
commit a4c62a3fee breaks SILC plugin

### ISSUE THREAD

**Issue by jnh** [irssi/irssi#156]
I bisected an annoying regression in Irssi 0.8.17 with the SILC plugin to:
commit a4c62a3fee26761ff909e7fb01f372484db3057f
Author: Ailin Nemui ailin@esf51.localdomain
Date:   Sun Jun 8 02:18:57 2014 +0200

```
speed up window_item_find by interning name and removing call to channel_find
```

After this commit, every received SILC message winds up in the status window with garbage after the nick.  For example

21:02 < nick:$crap> fun fun

where $crap is a string containing non-ascii/invalid utf-8 characters, the highlighting of which is fairly goofy too.

**Comment by estan** [comment]
I'd like to ask you @jnh , you said "an obvious way to prefer external irssi headers over the irssi copy they bundle". Did they offer an non-obvious way? :) Because I'm running into this issue myself and would like to get it sorted somehow. How did you solve it? Just replace the Irssi bundled Irssi headers?

**Comment by jnh** [comment]
non-obvious, and ugly, but, assuming external irssi headers in /usr/include/irssi:

make IRSSI_INCLUDE=/usr/include/irssi CPPFLAGS='-I../../../src -I../../silc/core'

**Comment by estan** [comment]
Thanks!
