### ISSUE TITLE
docdir is ignored during installation

### ISSUE THREAD

**Issue by dimkr** [irssi/irssi#230]
doc/Makefile.in always installs the documentation to $datarootdir/doc/irssi.

Here's a fix:
```
diff -rup irssi-0.8.17-orig/docs/Makefile.in irssi-0.8.17/docs/Makefile.in
--- irssi-0.8.17-orig/docs/Makefile.in	2015-04-06 19:09:36.907777873 +0300
+++ irssi-0.8.17/docs/Makefile.in	2015-04-06 19:12:24.083781846 +0300
@@ -315,7 +315,7 @@ build_vendor = @build_vendor@
 builddir = @builddir@
 datadir = @datadir@
 datarootdir = @datarootdir@
-docdir = $(datadir)/doc/irssi
+docdir = @docdir@
 dvidir = @dvidir@
 exec_prefix = @exec_prefix@
 host = @host@
```

**Comment by ailin-nemui** [comment]
you should change `Makefile.am` instead, and make a Pull Request once you confirmed that default operation is not changed

**Comment by ailin-nemui** [comment]
@ahf close

**Comment by ailin-nemui** [comment]
do we really need to support CentOS 5? Is there any way to make this work on both? @dequis @dimkr

**Comment by dequis** [comment]
The only reason I wanted to test with centos 5 is that i wanted to ensure that we don't use any glib functions introduced after the oldest glib version we claim to support. I don't care a lot about it personally, but it's still covered by redhat's absurdly long 10 year support cycle (one year left, iirc), so some people do use it.

In the case of bitlbee I decided to drop support for centos 5 because I wanted to use some features introduced in glib 2.16 (hash table iterators, GChecksum for md5/sha1, g_strcmp0). Irssi uses g_strcmp0 and provides a macro implementation of it for older glib versions - i suspect that macro implementation was broken by recent patches that pass g_strcmp0 as a parameter, but didn't get around to confirm that.

No one complained so far but I guess we can't really expect people who use dinosaurs to test bleeding edge versions of the client of the past.

Anyway, dropping centos 5 support should be considered - this ticket might be the first decent reason to do it.

**Comment by dimkr** [comment]
@ailin-nemui I need this change to control docdir on a distro that uses a non-standard directory, not for CentOS 5.

**Comment by ailin-nemui** [comment]
I know, @GeertHauwaerts removed your change because it does *not* work on CentOS5 :-(

**Comment by GeertHauwaerts** [comment]
Then I guess we drop the support for CentOS5.

@ahf, agreed?

**Comment by dequis** [comment]
Submitted #300
