### ISSUE TITLE
Handling unknown commands

### ISSUE THREAD

**Issue by CuleX** [irssi/irssi#261]
irssi currently rejects any commands not known to it. This is currently mitigated by [dispatch.pl](https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/dispatch.pl) for anyone who needs/want to send commands to the server regardless of irssi's blessing.

The behavior dispatch.pl introduces is arguably more sane than the default: Most (if not all) IRCds return an error message if an unknown command is sent, making the effort to do it on the side of irssi effectively redundant.

Furthermore, many IRC networks provide server-side aliases for services commands which have the added benefit of also verifying if the message target is also on the correct server (e.g., ```NS info``` gets aliased to ```PRIVMSG NickServ@services.server :info```), reducing the effects of a malicious IRC operator (or even a malicious user on sufficiently misconfigured networks) impersonating services during a netsplit. Some guides may assume that those aliases work out of the box.

Many IRCds have custom IRC operator commands as well, which must be worked around using ```/quote``` to access them in the first place.

I therefore propose dropping the behavior where commands unknown to irssi get trapped; alternatively, make a configuration option to disable this behavior, removing the need to depend on an external script.

**Comment by GeertHauwaerts** [comment]
This would indeed be nice, I tried to implement that 8 years ago; but it was rejected then (and I can't remember the reason)

I personally do not object to have this as a feature; @ahf, what do you think?

**Comment by dequis** [comment]
For the record: ["Why I don’t like dispatch.pl" by Wouter Coekaerts](http://wouter.coekaerts.be/irssi/dispatch)

**Comment by CuleX** [comment]
If I may address those arguments...

1. "If you have 5 seconds lag, you only see after 5 second" -- This may be an argument for irssi on smartphone on a shoddy connection; smartphones aren't exactly my area of expertise. The times of shoddy ISDN lines should, however, be over by now. The lag argument could be addressed with a configuration option.
2. "I don’t like ‘breaking’ the protocol." -- Wouter Coekaerts's examples then proceed to enumerate with protocols that are not meant to deal with considerable amounts of human input. Furthermore, there's no actual problem with what he calls breaking the protocol: IRCds are used to those things.
3. Is yet another edge case that could easily be solved with properly autoloading the script, storing the password in a file so that it doesn't need to get input every time or just naming the script's commands something else. Furthermore, I doubt many IRCds have both the audacity and the storage space to store unknown commands sent to it. The issue of sensitive data going over the wire at all can be mostly avoided by using TLS, which is considerably widespread; significant resistance only coming from UnderNet and QuakeNet.
4. "The commands you use via dispatch can’t get tab-completed" -- That's true, but on the other hand, maintaining a database of ever-growing commands clearly hasn't happened on the irssi end, thus it seems to be an unreasonable amount of work to track every new command and server-side alias.
5. "The alternative, ‘/alias pom quote pom’ for every (pom) command irssi doesn’t already know, takes less then a minute to set up, and doesn’t have any of the above disadvantages." -- It does have a disadvantage that users seeking aid in an IRC network's help channel may run into trouble when being told to do something and first need to be taught how to set up those aliases. Plus there may be conflicting server-side aliases: HS may be an alias for messaging HostServ on one network but HelpServ on another.

**Comment by capi** [comment]
@CuleX addressing your reply to 3: you can't protect against the _server_ seeing the sensitive data (and potentially storing it in a logfile for debugging unknown attempts, hacking attempts, etc.) by using TLS.

I personally don't like the idea of data going over the wire (unencrypted or encrypted) to whatever server is currently active, just because I made a typo. I do see, though, that some people would like suche an "auto-quoting" feature of unknown commands.

**Comment by ailin-nemui** [comment]
not everything needs to be implemented in irssi core

**Comment by user2334** [comment]
just use /quote command ?

**Comment by ahf** [comment]
I use, and have always used, `dispatch.pl` (which I got from @tomaw back in the days) and I must admit I missed Xchat's way of doing things when I moved from Xchat to irssi, but I can understand @coekie's point's above. I'm not fully sure this belongs in the core.

If someone is to do it, it would at least have to be protected behind a setting entry which by default is disabled.

**Comment by flaw600** [comment]
Just to state the obvious, many users on various forums and help channels have wondered why the general behavior of dispatch.pl wasn’t already in the core. At the very least auto-quoting commands, namely because many networks request commands not recognized by irssi but are by default recognized by many other client types. Namely, Mibbit. Regardless of what you may think of Mibbit being a ‘client’ it is undoubtedly true that it is the most popular choice when it comes to new/novice users mainly because of ease-of-use. Part of this is auto-quoting/recognizing commands that irssi doesn’t. 

I happen to think that the points brought up by @CuleX are quite valid except perhaps for point 3 concerning security. That being said, point 3 doesn’t seem to be enough of a concern to prevent introducing this type of request in other clients’ cores or others’ devs have taken it upon themselves to provide a decent enough workaround. At any rate, my main criteria when it comes to a feature is “does this make things significantly easier upon a novice user,” and when comparing it to that, this Issue seems to check out. That’s just my humble opinion, however.

**Comment by ailin-nemui** [comment]
the biggest issue is that we cannot know how to quote the command properly, that's why this cannot be implemented.

**Comment by flaw600** [comment]
You could literally just call /quote
