### ISSUE TITLE
/msg +#channel (wallvoices) incorrectly shows up as Nick:@#channel

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#291]

**Comment by ailin-nemui** [comment]
@LemonBoy you may know about this

**Comment by LemonBoy** [comment]
Here's the culprit [1] and it's evil sibling [2]. As we strip all the prefixes before emitting the signal, we should just print the channel name or send the original string and show the possibly ugly name.
As a bonus, here's a brainfart [3], it should just return `target` instead of false (why did an integer got promoted as pointer with no warning at all ?)

[1] https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-irc-messages.c#L78
[2] https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-irc-messages.c#L95
[3] https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-irc-channels.c#L58,L59

**Comment by dequis** [comment]
Also relevant https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-events.c#L59

I guess yeah the skip prefix should be moved to the op_public handler instead.

Not sure what's the deal with own_wall, should look into that one separately.

>(why did an integer got promoted as pointer with no warning at all ?)

Probably because FALSE is a constant 0 and that is the same as returning NULL.

**Comment by dequis** [comment]
Went ahead and did it myself, #295
