### ISSUE TITLE
port dane to getdns

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#417]
?

**Comment by ailin-nemui** [comment]
@ahf

**Comment by ailin-nemui** [comment]
@LemonBoy may also be interesting instead of gio as far as I understand

**Comment by LemonBoy** [comment]
We might want to prioritize this since the user `kazoo` has reported that irssi isn't able to build with dane support [1]. Apparently the function `val_dane_check` has vanished in between the `2.0` and the `2.1` release with no indication of that and no hint about how to replace it (it's even still present in the manpages!). 
There are some more votes for using getdns [2].

[1] http://pastebin.com/jiexS3g5
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797470

**Comment by dequis** [comment]
Not being able to build with dane support sounds like a feature, not a bug.

`*hides*`

**Comment by oerdnj** [comment]
I would definitely recommend using getdns instead of dnsval (with both my DNS and Debian hats on).

**Comment by LemonBoy** [comment]
[ldns](http://www.nlnetlabs.nl/projects/ldns/) is another great-looking alternative.

**Comment by dequis** [comment]
5a04430998ada5ae800aa0a88638206de51287ca killed DANE
