### ISSUE TITLE
potential terminal state not reset after 2x suspend

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#450]
testing with zsh, after suspending irssi 2x with Ctrl+Z, I don't get working Ctrl+C anymore (for example if I then launch cat). Curiously enough it doesn't seem to happen in bash.

**Comment by dequis** [comment]
Is this actually a regression from 0.8.17 to 0.8.18?

**Comment by ailin-nemui** [comment]
I think this one is not a regression just a regular bug

**Comment by dequis** [comment]
In that case, can we leave it after 0.8.18a? The two PRs that link to this bug have changes that are small and subtle but look like they could break things in crappy platforms.

...in practice it turns out that we *have* to make a release to get people to bother to test things, sigh. But this one looks riskier than the others.
