### ISSUE TITLE
Bold colors/fonts not working correctly under FreeBSD

### ISSUE THREAD

**Issue by modk** [irssi/irssi#463]
Hi, I encountered a strange difference after comparing the fonts and colors of two irssis with the same confing, one running under a Ubuntu 12.04 and one under FreeBSD 10.2.
Whenever a theme uses a bold font (e.g. %W), the color is changed (my setup uses different colors for bold and non-bold default fonts) but no bold font is used. When I manually put a %9 before the %W it works correctly (different color as well as bold now).

Digging through the code I could not immediately spot where this goes wrong. Any ideas?

**Comment by LemonBoy** [comment]
What irssi version and what terminal emulator are you running?

**Comment by modk** [comment]
irssi 0.8.17 (20141011 1044), XTerm(324)

**Comment by ailin-nemui** [comment]
different TERM. %W is not bold, it is bright. Some terminals emulate bright colours with bold. Bright colours will be emulated with bold on 8-colour terminals.

**Comment by mattvz** [comment]
This is actually a FreeBSD limitation due to its use of termcap rather than terminfo. With a 256color TERM FreeBSD's termcap has AF=\E[38;5;%dm which in most terminals will not make bold colors bright unless set explicitly.
One workaround is to launch irssi inside screen with:
attrcolor b ".I"
in your .screenrc.

**Comment by mattvz** [comment]
I checked around, Konsole and modern libvte-based terminals (tested with libvte-0.42.4) exibit xterm's behavior on FreeBSD. urxvt, mintty, and libvte-0.2x based terminals (like LXTerminal) don't. urxvt and mintty (and I imagine PuTTy) at least make bold vs bright configurable, unlike Konsole/libvte. If you don't care about 256color support, you could just launch irssi with TERM=xterm.

**Comment by ailin-nemui** [comment]
Thanks for the insight, mattvz. The termcap would explain the difference, since terminfo's setaf is `setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m`, i.e. it chooses the \E[3Xm code for configuring the foreground and only uses \E[38;5;Xm for the colours beyond 16. These difference in code may then lead to terminals rendering the colours bold or not.

**Comment by ailin-nemui** [comment]
reopen if you have any further questions
