### ISSUE TITLE
GRegex not utf8 compliant?

### ISSUE THREAD

**Issue by KoffaFI** [irssi/irssi#636]
Trying to match utf8 characters with a single "." in the lastlog fails. 
Example: having "RÖYH" in the lastlog, using "/lastlog -regexp R.YH" returns nothing.
Using "/lastlog -regexp R..YH" returns the relevant line.
Affects 1.0.0., works as expected in eg. 0.8.17-1+deb8u3.

**Comment by dequis** [comment]
Same thing written diferently from the other dupe:

> As reported by Koffa:
> Running `/lastlog -regexp R.YH` doesn't match 'RÖYH' (my interpretation)
> `Koffa  ┃ I have 'term_charset' UTF-8 but still /lastlog -re considers eg. ö two characters...`
> `vague ┃ Koffa, which irssi version?`
> `Koffa  ┃ 1.0.0`
> `Koffa  ┃ tried with 0.8.20 and it works as expected`
> 
> I test it on 0.8.20:
> `Lastlog:`
> `Koffa ┃ but try to match R.YH`
> `Koffa ┃ with this: RÖYH`
> `End of Lastlog`

**Comment by ailin-nemui** [comment]
Investigate removing G_REGEX_RAW from https://github.com/LemonBoy/irssi/commit/5dcf291f2144564363f734dba15760d3a82b61c2 or maybe make it conditional on the terminal type. Needs special attention to whether non-utf8-clean textbuffer results in any undefined behaviour (like incoming iso encoding with recode disabled)..

**Comment by ailin-nemui** [comment]
after studying the glib source, GRegex turns on PCRE_UTF8 | PCRE_NO_UTF8_CHECK so that means we need to take extra care of validating both the regex and the textbuffer content if we don't want to run into the GL#3 issue.

**Comment by dequis** [comment]
I've done some testing with afl on the above ([test programs](https://gist.github.com/dequis/14fbf3600ebaa3d40b11175d701d48a3)). Findings:

* We do need to validate both regex and textbuffer.
* Not validating either leads to segfaults.
* Passing invalid utf8 when using `G_REGEX_RAW` is safe (I just gave it 30 minutes in contrast to the other modes which failed in less than a minute. Not claiming PCRE is perfect, but others have fuzzed it)
* We don't have control over the `PCRE_NO_UTF8_CHECK` flag. `G_REGEX_OPTIMIZE` has the same value as `PCRE_NO_UTF8_CHECK` and the implementation takes advantage of that to be clever, but removing `G_REGEX_OPTIMIZE` does not prevent `PCRE_NO_UTF8_CHECK` from being enabled.
* But `PCRE_NO_UTF8_CHECK` doesn't matter a lot since it just results in failing to process the string, just like calling g_utf8_validate before.


If we go with validation and you're trying to ignore some text on a pattern, other people can avoid the ignore by adding invalid utf8. I don't like validation.

On the other hand, we can't reliably know at compile time when utf8 is needed (the example from OP is all ascii).

Posix regexps (the glibc implementation) appear to not care about anything. I tried to match:

    a.c\x80\x81

Against:

    a\xc3\xa1c\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89

The first four bytes are utf8 for `aác`, followed by very invalid utf8. It matched, taking the á as a single character and completely disregarding the invalid utf8 in both the regexp and the matched text. PCRE, in contrast, gives up with both that regex and that body.

Ideas:

* Keep two compiled versions? UTF-8 and raw, skipping the former if even the pattern is invalid. So validate when matching and if it doesn't pass use the raw one.
* Iterate over the matched text with `g_utf8_find_next_char()` and `g_utf8_get_char_validated()`, replace invalid parts with � before passing them to gregex.
* Runtime switch to use posix regexps (with the caveat that the implementations in some operating systems might be worse than PCRE). Recompiling all the regexps doesn't seem too bad now.

**Comment by ailin-nemui** [comment]
@KoffaFI feel welcome to test my proposal ^

**Comment by ailin-nemui** [comment]
#653 does remapping to Private Use Area
- benefit: we can reverse the mapping as long as noone sends PUA on the line (that cannot be guaranteed however)
- disadvantage: obscure

- @dequis suggests to remap everything onto Latin1 instead
  - benefit: does byte to charcode mapping
  - disadvantage: not easy to reverse, need to convert either the whole text buffer or think of something else

- replace everything with <?>
  - benefit: it's safe
  - disadvantage: permanent information loss, cannot target binary data with ignores or hilights

- other ideas??? @LemonBoy ?

**Comment by LemonBoy** [comment]
- Remove GRegex and admit that making the switch was a mistake...The original PR was stalled because of the utf8 concerns which were **not** resolved at the time it got merged.
- The remapping business is quite the hack, a cleaner solution would be to always keep the text stored as utf8 but I suppose that's too much work.

I'd go for the first.

**Comment by dequis** [comment]
>I'd go for the first.

Hmm yeah maybe.

* Disable GRegex by default, but keep the compile time switch to let non-linux platforms enable it. The regex implementation of glibc turned out to be great for our use case, but the same can't be said of other libc implementations.

**Comment by egmontkob** [comment]
Just for the record: in Midnight Commander we had to come up with a wrapper in front of `g_regex_match_full()` for the same reason, that is, to sanitize potentially invalid UTF-8. (We don't sanitize the pattern since that's typed in from the keyboard, so in UTF-8 it should really be valid UTF-8.) Feel free to reuse that wrapper if you wish.

**Comment by ailin-nemui** [comment]
thanks for the info, would have thought of replacing invalid utf-8 with '\0'
