### ISSUE TITLE
INFO: Source code lines indented with spaces and/or having trailing whitespace

### ISSUE THREAD

**Issue by Stevie-O** [irssi/irssi#681]
After @ailin-nemui 's request re: whitespace fixing on #680, I threw together a quick script to detect places in irssi's source tree that are indented with spaces instead of tabs (which appears to be the norm.)

https://github.com/Stevie-O/irssi/commit/092d83d56228bd9f7eda8e0e0078d0815bb54574 is the result.

Since applying such a change will cause massive merge conflicts with existing pull requests, I didn't create this as a pull request; if you want to merge it, you'll most likely want to deal with as many existing PRs as possible and then set aside a point to deal with the whitespace.

**Comment by ailin-nemui** [comment]
Well thank you, so far I did not want to introduce such a huge style correction commit. Maybe we should just do it and then be done with it?

**Comment by dequis** [comment]
Yeah I don't know either. Maybe it's better to use clang-format or uncrustify and also fix other style inconsistencies while we're at it (and make braces mandatory even for single statements). Or maybe it's better to apply this and hope it's significantly less intrusive than other changes.

FWIW when I did this in bitlbee I committed it with `--author="Indent <please@skip.me>"` so that it's easier to skip that change when doing git blame

**Comment by Stevie-O** [comment]
Well, I figured you guys wouldn't want to just apply this; that's why this is just issue and not a PR.  I just wanted people to be able to see what such a cleanup would entail.

**Comment by ailin-nemui** [comment]
hi, I will close this for now but thanks for the info!
