### ISSUE TITLE
GCC: error: unrecognized command line option '-fsanitize-coverage=trace-pc-guard'

### ISSUE THREAD

**Issue by sheeit** [irssi/irssi#727]
I think it should be `-fsanitize-coverage=trace-pc` instead of `-fsanitize-coverage=trace-pc-guard`, because that's what's in the GCC manpage.

The problem is with `configure.ac` line 330:
```sh
	if test -z "$SANFLAGS"; then
		SANFLAGS="-g -fsanitize=address -fsanitize-coverage=trace-pc-guard"
	fi
```

**Comment by dequis** [comment]
fe-fuzz only supports clang.

Are you planning to fuzz irssi?

**Comment by josephbisch** [comment]
As you can see from the excerpt from `configure.ac` that you pasted, you can override the `SANFLAGS` variable if you are using a compiler that doesn't support `-fsanitize-coverage=trace-pc-guard`, and therefore want to change to `-fsanitize-coverage=trace-pc`. I welcome PRs that make the configure script run through common values for sanitize-coverage and detect which one(s) the compiler supports and use that by default. However, since last time I checked, GCC support in libfuzzer wasn't great, I don't see much reason for anyone to spend time to support building the libfuzzer-based Irssi fuzzer with GCC. But `sanitizer-coverage` support detection is still useful, because people may be running older versions of clang that also don't support `trace-pc-guard`.
