### ISSUE TITLE
Irssi terminal in inconsistent state after ignored suspend

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#733]
When irssi is not opened from a shell, for example running as top level inside tmux/screen/urxvt, using ^Z to suspend puts irssi into an inconsistent state, probably because the terminal is never resumed (no SIGCONT)  although the suspend was ignored.

Possibly related / caused by #452 (which came from discussion in #450 )

reported by Jaga

regression since 1.0.0

**Comment by ailin-nemui** [comment]
@LemonBoy do you see any negative effects of reverting ?

**Comment by LemonBoy** [comment]
Reverting everything isn't really a solution, we should rather investigate what's wrong and try to come up with a fix.
How does one reproduce this problem?

**Comment by dequis** [comment]
`screen irssi` (that is, launching it directly inside, without a shell in the middle) then ^Z for the default suspend keybinding. Reliably leaves the terminal config in stopped state.

The thing about #450 is that it was fixed by two tickets, #452 and #457. Both were merged for the 1.x branch, but only latter was included in 0.8.19. That didn't cause issues, but now we get this issue with people using 1.x.

And the appearance of the code deleted by #452 sounds like someone was doing something weird to workaround some not very well explained issue. And I think this issue is that we uncovered that again.

So far that's what's clear. I'm not 100% certain on the race conditions involved. Or what was fixed by #452, or how. Or its relationship with #457. I think nei has a better grasp on that, but I personally never found a way to reproduce the race condition.
