### ISSUE TITLE
testing irssi

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#767]
- unit tests
- complex tests

- Where should the tests be stored?
  - I would say separately from the sources, maybe in a root tests/ or in a tests/ folder in each sourcefile dir?
- what framework should we use, if any?
  - my immediate suggestion would be glib
  - https://github.com/GNOME/json-glib/tree/json-glib-1-2/json-glib/tests
- build system integration
  - In my opinion autotools is given (`make check`)

| | |
| --- | --- |
|  @dequis  |  i'm not sure. assert() is a bit raw  |
|  |  glib has a fairly basic test framework  |
|  |  outside of src/ would be nice  |
|  @ahf  |  glib's test framework is very OK IMO  |
|  @LemonBoy  | my main concern is about the testing fixtures, are we going to use netcat and some perl script to feed the test cases to irssi? |
| @ailin-nemui | it's a good question |
| | I think one possibility may be a perl script or mini ircd, but I dont know |
| @LemonBoy | next question is, do we want to test fe-text or do we need a whole new fe-test frontend? |
| @ailin-nemui | well for unit tests we can even test partial things like @horgh did in his modes parser PR |
| | without the need to any frontend. but maybe we can involve/evolve fe-fuzz to run the irc-server-like tests? |
| @LemonBoy |  I think the latter is better to automate the testing process, ui tests aren't *that* important and can come later |
| | in-module tests are nice but I think we also need something to handle more complex test cases where there are more parts that are involved |
| | recycling the fe-fuzz machinery is a nice idea |
| @ailin-nemui | eventually I would like to be able to test the frontend also, for example as I work on the split windows, or there is this nasty bug I'm trying to find - #745 - there it would need to test the textbufferview more or less |

-> #766

**Comment by ailin-nemui** [comment]
so far there are no tests in irssi. we should have tests for all kinds of pieces.

Especially I would like to see added
- test cases for any bugs we fix (regression tests) as well as
- general behaviour tests where it can be clearly expressed (maybe protocol module specific, maybe more generic).

That may for example surround the state of objects, the behaviour of the formatting/unformatting code, colour code compression, maybe also the emitted events ("signals"). It may also be needed to start a mainloop.

Just going through the list of already merged PRs makes a lot of candidates that could be tested.
Futhermore test cases could also be derived from work done by the fuzzing efforts

**Comment by ailin-nemui** [comment]
@horgh feel free to discuss also on IRC

**Comment by horgh** [comment]
GLib's testing framework looks decent. [This example](https://github.com/GNOME/json-glib/blob/master/json-glib/tests/array.c) is pretty simple. One tradeoff using something like this is there might be a learning curve for contributors, but I guess that's inevitable no matter what.

Regarding tests outside of `src/`: We could have subdirectories corresponding roughly to the code you test, for unit tests at least. For the one I wrote, it could go under `tests/irc/core` for example. This could give some organization. Would we want a naming scheme for the test programs too? e.g. corresponding to a `.c` file if it's testing functions in one in particular.

I'm not sure the best way to test things involving the network. Spinning up a real ircd might be doable. Interesting problem! Sounds like the fe-fuzz way would be good to try.

**Comment by josephbisch** [comment]
I wish I started with better naming for fe-fuzz or some directory structure like you mention. Because right now I use irssi.c and have a binary named irssi-fuzz. Which isn't descriptive of which part of the code is actually being tested. So I agree about the directory structuring and naming for these tests.

The difficulty of testing of things involving the network is (part of) the reason I have been slow to add more to fe-fuzz. For fuzzing with fe-fuzz on oss-fuzz it doesn't look like running an ircd is an option, but that could work for this. I think it would be even better if we can mock the network stuff, so it doesn't actually go over the network. The network mocking stuff could also be used for fe-fuzz.

It is possible to add a sort of "wrapper" or "driver" for the fe-fuzz fuzzer that implements a main function that calls LLVMFuzzerInitialize once and then LLVMFuzzerTestOneInput for each test input. So it should (at least in theory) be possible to just implement fuzzers that we can also call with a fixed set of inputs that we know the expected output of. But like I mentioned above, there are requirements for oss-fuzz (such as not being able to run the ircd in the background) that may limit our ability to create these regular tests if we try to make every test also fuzzable.

So there are two options:

1. Use fe-fuzz, but mock up the networking stuff, so that we don't have to run a separate ircd binary and therefore fe-fuzz can still be used with oss-fuzz.
2. Use something other than fe-fuzz for these tests or make a copy of fe-fuzz for these tests.

**Comment by LemonBoy** [comment]
> I think it would be even better if we can mock the network stuff, so it doesn't actually go over the network.

We can use a unix socket since those are already supported, we'd still need to run a separate server though.

> Spinning up a real ircd might be doable.

That, or we could use some scripts to "simulate" one, or just use `cat testcase | nc -l 6666` :)
I think that, whatever the solution we choose, we'd still need a framework (a-la tcl's `expect` ?) to simulate some "complex" interactions between the ircd and irssi.

If `fe-fuzz` is bound by restrictions imposed by the use in `oss-fuzz` I'd say we can just create a `fe-test` one, the added maintenance is small enough and is greatly compensated by having some tests.

Using glib's testing harness is fine by me too.
One minor nit is that it doesn't support junit's xml format out of the box, and travis doesn't parse the results at all, so we're stuck with no nice test results so ¯\\\_(ツ)\_/¯

**Comment by ailin-nemui** [comment]
we should consider sending the fixtures directly from our test C program to irssi. I'm not 100% sure but I think autotools will display a coloured test result as part of make check
