### ISSUE TITLE
weechat.look.prefix_same_nick in irssi?

### ISSUE THREAD

**Issue by eti0** [irssi/irssi#800]
Wondering if having a setting like weechat's `look.prefix_same_nick` would be possible to implement in irssi?
Even a script would be fine, I have been searching for an alternative for a while and couldn't find one.

To illustrate what I mean:
irssi:
![2017-12-18-21 59 05](https://user-images.githubusercontent.com/14180792/34127712-563e645a-e43e-11e7-8ead-dfee6debb183.png)

weechat:
![2017-12-18-21 58 49](https://user-images.githubusercontent.com/14180792/34127694-50aa5c74-e43e-11e7-8aad-585c79383950.png)

The nicks don't repeat themselves on the weechat screenshot, instead there's just a char indicating that it's a new message but from the same user.

**Comment by bcattaneo** [comment]
Hey @eti0 
I love your idea so I just sent this pull request: https://github.com/irssi/scripts.irssi.org/pull/455
I think it does exactly what you wanted, let me know what you think.

Notice this would break "nickcolor.pl", that's why there's also a new nickcolor's fork in my commit ("nickcolor_with_prefix.pl") with this new functionality

**Comment by eti0** [comment]
hey, that's really awesome, thanks a lot!
do you maybe know how i could truncate the nicks with this script aswell?
my old formatting was:
`pubmsg = "{pubmsgnick $nickalign$2 {pubnick $nickcolor$[7]0$nicktrunc}}$1";`
and i'm not quite sure how to get that same effect now.

cheers

**Comment by bcattaneo** [comment]
Hello @eti0.
Could you show me your modified version?
I'll be sending a new pull because instead of a nickcolor.pl fork, ailin suggested adding prefix to nickcolor itself (as an optional functionality).

**Comment by eti0** [comment]
well i didn't modify the script actually since i don't know how to
here's what my irssi currently looks like:

![image](https://user-images.githubusercontent.com/14180792/34620849-317e4e5c-f247-11e7-92b2-52cfbba32537.png)

and here's my [.theme](https://x.eti.tf/XXY7Q.theme).
so what i'm wondering is how to achieve this effect with your script aswell, i'm using nickcolor_expando.pl at the moment.

**Comment by bcattaneo** [comment]
Hello @eti0 !
Would it be possible for you to switch to "nickcolor.pl"? because this can't be made on expando.
If so, I just uploaded a new version for you to test:
https://raw.githubusercontent.com/bcattaneo/scripts.irssi.org/nickcolor/scripts/nickcolor.pl

You will have to unload both "prefix_same_nick.pl" and "nickcolor_expando.pl", and load this one instead. It has two new functionalities: nick truncation and of course nick prefix.

`/script load nickcolor.pl`
`/set nickcolor_enable_prefix ON`
`/set nickcolor_enable_truncate ON`
`/set nickcolor_prefix_text [10 spaces here]` (10 spaces, that should do it fine on your theme)
`/set nickcolor_truncate_value -7` (you had this same truncate value on your theme)

It looked like this on my test:
![testprefix](https://user-images.githubusercontent.com/2736402/34635419-bcaec684-f26d-11e7-91d9-448527766679.png)

Btw I liked your theme!
Let me know if it worked out for you, and I'll then submit a pull request.

**Comment by eti0** [comment]
thank you so much, that is just so awesome.
you should definitely submit a pull request!

should i close the issue now?

**Comment by bcattaneo** [comment]
Hey @eti0 
Sure I think you can close it now. I noticed /me messages didnt reset prefix nickname, so you may want to download this last version with the fix: https://raw.githubusercontent.com/bcattaneo/scripts.irssi.org/c5a0ddc5b7e5eb7aa5197db10daca7dbe7743bf4/scripts/nickcolor.pl

Thanks!
