### ISSUE TITLE
Netsplits don't show in all windows where users split

### ISSUE THREAD

**Issue by nvisser** [irssi/irssi#809]
The fixes in #465 seem to have caused split users to only show as splitting in certain windows, whereas the expected behavior is to show them in every channel they split from. There appears no such split message at all in some windows. If you experience this same issue please share all the knowledge you have about the situation so this can be fixed.

**Comment by ailin-nemui** [comment]
here's what I think is going on: when the netsplit is announced in a specific channel (because of a public message to that channel, skipping the 5 second timeout), using filter_channel, it will skip over all the non-matching channels. but before it does that, it will already mark the whole split as printed. oops

**Comment by ailin-nemui** [comment]
@GinjaNinja32 @dwfreed @nvisser does it not show JOINS? any observations about that?

**Comment by ailin-nemui** [comment]
can you try #812

**Comment by nvisser** [comment]
I'm running #812 right now, will update this issue when I can split some servers.
