### ISSUE TITLE
OTR plugin: /otr authq usability is a bit confusing

### ISSUE THREAD

**Issue by wilhelmy** [irssi/irssi#893]
If I read things correctly, `/otr authq [QUESTION] SECRET` means that the question goes into square brackets so that it can contain spaces. It does look like a command option though. I think quotes and updated documentation like `/otr authq "Favourite IRC client?" "irssi is definitely the best"` would be better?

**Comment by vague666** [comment]
@ahf

**Comment by vague666** [comment]
Although, are you talking about the module or the built-in functionality?

**Comment by dequis** [comment]
Yeah uh, where did you see that? I don't see square brackets anywhere

```
$ ag authq
docs/help/in/otr.in
17:AUTHQ <question> <secret>
20:    Example: %9/otr authq "My question is" "this is the secret"%n
88:%9/otr auth <shared-secret>%n OR %9/otr authq "A question" <shared-secret>%n

docs/help/otr
17:AUTHQ <question> <secret>
20:    Example: %9/otr authq "My question is" "this is the secret"%n
82:%9/otr auth <shared-secret>%n OR %9/otr authq "A question" <shared-secret>%n

src/otr/otr-fe.c
228:static void cmd_otr_authq(const char *data, SERVER_REC *server, WI_ITEM_REC *item)
316:    command_bind("otr authq", NULL, (SIGNAL_FUNC) cmd_otr_authq);
338:    command_unbind("otr authq", (SIGNAL_FUNC) cmd_otr_authq);
```

From the source I can confirm that both args are required, fwiw

**Comment by dequis** [comment]
Answering my own question with the obvious answer: in the third party plugin, pre-merge, the one from https://github.com/cryptodotis/irssi-otr instead of the one in this repo

It does indeed have a weird-ass syntax to use square brackets instead of quotes (`utils_io_extract_smp` is ugly as hell, not surprised ahf nuked it), and the question is also required in that case (it gives up if the first character of the first parameter isn't `[`)

None of that exists in the merged version of the otr plugin, you just use quotes instead. If you see/need that you're using the old pre-merge third party plugin instead.

**Comment by wilhelmy** [comment]
Turns out, this is really still irssi-1.1.1 with irssi-otr 1.0.2. I thought there was already a release which includes OTR support. Sorry for making so much noise :(
