### ISSUE TITLE
ERROR: Couldn't create $HOME/.irssi directory

### ISSUE THREAD

**Issue by joekendal** [irssi/irssi#910]
```shell
$ irssi
** (irssi:14528): ERROR **: <timestamp>: Couldn't create $HOME/.irssi directory
Trace/breakpoint trap (core dumped)
```
I can manually bypass this error however:
```shell
$ mkdir $HOME/.irssi
```

**Comment by dequis** [comment]
Why did you close this? Did you figure it out?

**Comment by joekendal** [comment]
@dequis the SSL timeouts were caused by my firewall. The error creating the irssi directory was only resolved by manually creating the .irssi folder. But still this is strange that it cannot do so by the program itself, so is maybe a bug that should be looked into. For reference, I encountered this bug on Ubuntu 18.04 with the upstream irssi release

**Comment by dequis** [comment]
Quoting myself on #925:

>IMO we'll never know what happened there, and it's not very important either, but for the next time we can show the actual reason the mkdir failed.
>
>The fact that it aborts and generates coredump is a bit awkward but `g_error` really is the handiest way to show this sort of thing and quit, so that's fine I think.

So, closing this. If it ever happens again we'll know why.

**Comment by skully** [comment]
I know I'm replying to a 7-year-old issue, but I recently ran into the same error on Ubuntu 24.04.

At first I assumed it was a normal filesystem permission problem, but ownership and permissions on $HOME were correct. Running strace showed that Irssi was getting EACCES when trying to create its configuration directory:

mkdir("/home/user/.irssi", 0700) = -1 EACCES (Permission denied)

That led me to check the kernel log, where AppArmor denials showed up:

apparmor="DENIED" operation="mkdir" profile="irssi"
apparmor="DENIED" operation="open" profile="irssi"
apparmor="DENIED" operation="exec" profile="irssi"

In my case, the profile only allowed access to files under ~/.irssi/**, which made the failures look like ordinary filesystem permission problems. The actual cause was the AppArmor profile shipped by the distribution, not the filesystem permissions themselves.

So if someone finds this issue while seeing Permission denied despite correct ownership and mode bits, it may be worth checking strace, dmesg, or the audit logs for AppArmor denials.
