### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [irssi/irssi#932]
I would like to point out that identifiers like “[`__COMMON_H`](https://github.com/irssi/irssi/blob/071ada830bd77055107220a420c96b41702f8cc2/src/common.h#L1 "Update candidate")” and “[`__UTF8_H`](https://github.com/irssi/irssi/blob/0d8632943d8fb526fbd4d853c86294d0037c43f6/src/core/utf8.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by dequis** [comment]
Does this have any practical consequences?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by jillest** [comment]
A practical consequence could be that some compiler or operating system implementation uses these names (which are in the namespace reserved for them) for their own purposes, such as include guards for their headers. This could cause mysterious errors because a header file is skipped because it has supposedly already been included.

A convention like `IRSSI_COMMON_H` or `IRSSI_COMMON_H_INCLUDED` would be safer.

**Comment by ailin-nemui** [comment]
as we've never heard of any such problems I'd say this is purely academic

**Comment by ailin-nemui** [comment]
Fixed

**Comment by dequis** [comment]
(with https://github.com/irssi/irssi/pull/1040 )
